[2022-04-07 19:24:37,340] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2017-05-01T00:00:00+00:00 [queued]>
[2022-04-07 19:24:37,388] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2017-05-01T00:00:00+00:00 [queued]>
[2022-04-07 19:24:37,388] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:24:37,389] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:24:37,389] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:24:38,408] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2017-05-01 00:00:00+00:00
[2022-04-07 19:24:38,540] {standard_task_runner.py:52} INFO - Started process 3826 to run task
[2022-04-07 19:24:38,622] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2017-05-01T00:00:00+00:00', '--job-id', '12890', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp9aia10n9', '--error-file', '/tmp/tmpnedoadew']
[2022-04-07 19:24:38,652] {standard_task_runner.py:80} INFO - Job 12890: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 19:24:39,119] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2017-05-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:24:39,579] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:24:39,753] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2017-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-05-01T00:00:00+00:00
[2022-04-07 19:24:39,758] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:24:40,710] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20170501T000000, start_date=20220407T192437, end_date=20220407T192440
[2022-04-07 19:24:40,969] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:24:41,100] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:17:59,352] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2017-05-01T00:00:00+00:00 [queued]>
[2022-04-07 22:17:59,393] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2017-05-01T00:00:00+00:00 [queued]>
[2022-04-07 22:17:59,393] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:17:59,393] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:17:59,394] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:17:59,796] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2017-05-01 00:00:00+00:00
[2022-04-07 22:17:59,825] {standard_task_runner.py:52} INFO - Started process 6175 to run task
[2022-04-07 22:17:59,851] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2017-05-01T00:00:00+00:00', '--job-id', '14154', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpb2tg1hbd', '--error-file', '/tmp/tmplkq4e2r3']
[2022-04-07 22:17:59,853] {standard_task_runner.py:80} INFO - Job 14154: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 22:18:00,112] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2017-05-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:18:00,314] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:18:00,392] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2017-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-05-01T00:00:00+00:00
[2022-04-07 22:18:00,395] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:18:00,937] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20170501T000000, start_date=20220407T221759, end_date=20220407T221800
[2022-04-07 22:18:01,001] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:18:01,123] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
