[2022-04-07 19:26:38,542] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-08-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:38,661] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-08-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:38,666] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:38,666] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:26:38,666] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:39,199] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2018-08-01 00:00:00+00:00
[2022-04-07 19:26:39,228] {standard_task_runner.py:52} INFO - Started process 4709 to run task
[2022-04-07 19:26:39,263] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2018-08-01T00:00:00+00:00', '--job-id', '13016', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpftr50e9h', '--error-file', '/tmp/tmpjva78ibd']
[2022-04-07 19:26:39,275] {standard_task_runner.py:80} INFO - Job 13016: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 19:26:39,573] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-08-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:26:39,876] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:26:39,934] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2018-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-08-01T00:00:00+00:00
[2022-04-07 19:26:39,936] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:26:40,713] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20180801T000000, start_date=20220407T192638, end_date=20220407T192640
[2022-04-07 19:26:40,802] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:26:40,916] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:19:32,748] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-08-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:32,788] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-08-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:32,789] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:32,789] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:19:32,789] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:33,084] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2018-08-01 00:00:00+00:00
[2022-04-07 22:19:33,109] {standard_task_runner.py:52} INFO - Started process 7015 to run task
[2022-04-07 22:19:33,131] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2018-08-01T00:00:00+00:00', '--job-id', '14276', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpw49_ko_5', '--error-file', '/tmp/tmp7zm8mbjo']
[2022-04-07 22:19:33,132] {standard_task_runner.py:80} INFO - Job 14276: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 22:19:33,320] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-08-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:19:33,470] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:19:33,526] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2018-08-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-08-01T00:00:00+00:00
[2022-04-07 22:19:33,529] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:19:34,029] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20180801T000000, start_date=20220407T221932, end_date=20220407T221934
[2022-04-07 22:19:34,162] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:19:34,332] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
