[2022-04-07 19:26:19,131] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:19,236] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:19,252] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:19,252] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:26:19,252] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:19,940] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task> on 2018-03-01 00:00:00+00:00
[2022-04-07 19:26:19,967] {standard_task_runner.py:52} INFO - Started process 4574 to run task
[2022-04-07 19:26:20,005] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task', 'scheduled__2018-03-01T00:00:00+00:00', '--job-id', '12994', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmph679k_bk', '--error-file', '/tmp/tmpnytkmc6t']
[2022-04-07 19:26:20,007] {standard_task_runner.py:80} INFO - Job 12994: Subtask create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
[2022-04-07 19:26:20,295] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:26:20,695] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-03-01T00:00:00+00:00
[2022-04-07 19:26:20,697] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:26:20,809] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:26:20,871] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_555573fd0b6512a7fb87d143aad46dce
[2022-04-07 19:26:21,690] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2153, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2119, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1560, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1498, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1488, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Could not cast literal "date" to type TIMESTAMP at [1:102]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_555573fd0b6512a7fb87d143aad46dce

[2022-04-07 19:26:21,744] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=load_to_BigQuery, task_id=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task, execution_date=20180301T000000, start_date=20220407T192619, end_date=20220407T192621
[2022-04-07 19:26:21,862] {standard_task_runner.py:98} ERROR - Failed to execute job 12994 for task create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task (400 Could not cast literal "date" to type TIMESTAMP at [1:102]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_555573fd0b6512a7fb87d143aad46dce
; 4574)
[2022-04-07 19:26:22,013] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-07 19:26:22,268] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:19:04,170] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:04,250] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:04,250] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:04,250] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:19:04,250] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:05,047] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task> on 2018-03-01 00:00:00+00:00
[2022-04-07 22:19:05,066] {standard_task_runner.py:52} INFO - Started process 6792 to run task
[2022-04-07 22:19:05,091] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task', 'scheduled__2018-03-01T00:00:00+00:00', '--job-id', '14240', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpgc0_qk95', '--error-file', '/tmp/tmpsz1xyh1_']
[2022-04-07 22:19:05,106] {standard_task_runner.py:80} INFO - Job 14240: Subtask create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
[2022-04-07 22:19:05,372] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2018-03-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:19:05,673] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-03-01T00:00:00+00:00
[2022-04-07 22:19:05,676] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:19:05,791] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:19:05,878] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2018_03_01T00_00_00_00_00_c8a1590123385a7ff0a7cb9813c3d7c5
[2022-04-07 22:19:08,239] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task, execution_date=20180301T000000, start_date=20220407T221904, end_date=20220407T221908
[2022-04-07 22:19:08,370] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:19:08,524] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
