[2022-04-05 23:18:18,847] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: IngestToGCP.processing_tasks_posts_answers.ingest_posts_answers_to_bucket scheduled__2010-11-01T00:00:00+00:00 [queued]>
[2022-04-05 23:18:19,082] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: IngestToGCP.processing_tasks_posts_answers.ingest_posts_answers_to_bucket scheduled__2010-11-01T00:00:00+00:00 [queued]>
[2022-04-05 23:18:19,082] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 23:18:19,083] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-05 23:18:19,083] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-05 23:18:19,321] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): processing_tasks_posts_answers.ingest_posts_answers_to_bucket> on 2010-11-01 00:00:00+00:00
[2022-04-05 23:18:19,509] {standard_task_runner.py:52} INFO - Started process 41666 to run task
[2022-04-05 23:18:19,605] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'IngestToGCP', 'processing_tasks_posts_answers.ingest_posts_answers_to_bucket', 'scheduled__2010-11-01T00:00:00+00:00', '--job-id', '9035', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dag.py', '--cfg-path', '/tmp/tmpbmweupq3', '--error-file', '/tmp/tmpzjpbvz4b']
[2022-04-05 23:18:19,606] {standard_task_runner.py:80} INFO - Job 9035: Subtask processing_tasks_posts_answers.ingest_posts_answers_to_bucket
[2022-04-05 23:18:20,848] {logging_mixin.py:109} INFO - Running <TaskInstance: IngestToGCP.processing_tasks_posts_answers.ingest_posts_answers_to_bucket scheduled__2010-11-01T00:00:00+00:00 [running]> on host 9fe4286b2855
[2022-04-05 23:18:21,541] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-05 23:18:21,740] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=IngestToGCP
AIRFLOW_CTX_TASK_ID=processing_tasks_posts_answers.ingest_posts_answers_to_bucket
AIRFLOW_CTX_EXECUTION_DATE=2010-11-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2010-11-01T00:00:00+00:00
[2022-04-05 23:18:24,383] {python.py:175} INFO - Done. Returned value was: None
[2022-04-05 23:18:24,490] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=IngestToGCP, task_id=processing_tasks_posts_answers.ingest_posts_answers_to_bucket, execution_date=20101101T000000, start_date=20220405T231818, end_date=20220405T231824
[2022-04-05 23:18:24,624] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-05 23:18:24,961] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
