[2022-04-07 19:21:54,334] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2015-02-01T00:00:00+00:00 [queued]>
[2022-04-07 19:21:54,504] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2015-02-01T00:00:00+00:00 [queued]>
[2022-04-07 19:21:54,504] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:21:54,505] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:21:54,505] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:21:55,382] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task> on 2015-02-01 00:00:00+00:00
[2022-04-07 19:21:55,409] {standard_task_runner.py:52} INFO - Started process 2618 to run task
[2022-04-07 19:21:55,451] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task', 'scheduled__2015-02-01T00:00:00+00:00', '--job-id', '12698', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmptfgwb2lw', '--error-file', '/tmp/tmphchv1fom']
[2022-04-07 19:21:55,464] {standard_task_runner.py:80} INFO - Job 12698: Subtask create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
[2022-04-07 19:21:55,779] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2015-02-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:21:56,292] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2015-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-02-01T00:00:00+00:00
[2022-04-07 19:21:56,294] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:21:56,349] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:21:56,390] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2015_02_01T00_00_00_00_00_91ce48d7961842c8338f2993c564f450
[2022-04-07 19:21:57,161] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2153, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2119, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1560, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1498, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1488, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Could not cast literal "date" to type TIMESTAMP at [1:102]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2015_02_01T00_00_00_00_00_91ce48d7961842c8338f2993c564f450

[2022-04-07 19:21:57,239] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=load_to_BigQuery, task_id=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task, execution_date=20150201T000000, start_date=20220407T192154, end_date=20220407T192157
[2022-04-07 19:21:58,124] {standard_task_runner.py:98} ERROR - Failed to execute job 12698 for task create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task (400 Could not cast literal "date" to type TIMESTAMP at [1:102]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2015_02_01T00_00_00_00_00_91ce48d7961842c8338f2993c564f450
; 2618)
[2022-04-07 19:21:58,196] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-07 19:21:58,324] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:15:18,922] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2015-02-01T00:00:00+00:00 [queued]>
[2022-04-07 22:15:19,022] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2015-02-01T00:00:00+00:00 [queued]>
[2022-04-07 22:15:19,025] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:15:19,026] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:15:19,026] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:15:19,720] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task> on 2015-02-01 00:00:00+00:00
[2022-04-07 22:15:19,787] {standard_task_runner.py:52} INFO - Started process 4884 to run task
[2022-04-07 22:15:19,841] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task', 'scheduled__2015-02-01T00:00:00+00:00', '--job-id', '13953', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp2w5dxmhz', '--error-file', '/tmp/tmp96s44br2']
[2022-04-07 22:15:19,842] {standard_task_runner.py:80} INFO - Job 13953: Subtask create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
[2022-04-07 22:15:20,210] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task scheduled__2015-02-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:15:20,449] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2015-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-02-01T00:00:00+00:00
[2022-04-07 22:15:20,451] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:15:20,466] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:15:20,504] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_badges_bq_create_badges_stack_overflow_data_partitioned_table_task_2015_02_01T00_00_00_00_00_61c8aaf555bfab77218e2c8b599f058d
[2022-04-07 22:15:22,830] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.bq_create_badges_stack_overflow_data_partitioned_table_task, execution_date=20150201T000000, start_date=20220407T221518, end_date=20220407T221522
[2022-04-07 22:15:22,864] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:15:22,905] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
