[2022-04-07 19:27:18,742] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task scheduled__2018-12-01T00:00:00+00:00 [queued]>
[2022-04-07 19:27:18,764] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task scheduled__2018-12-01T00:00:00+00:00 [queued]>
[2022-04-07 19:27:18,765] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:27:18,765] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:27:18,765] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:27:19,152] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task> on 2018-12-01 00:00:00+00:00
[2022-04-07 19:27:19,187] {standard_task_runner.py:52} INFO - Started process 5019 to run task
[2022-04-07 19:27:19,307] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task', 'scheduled__2018-12-01T00:00:00+00:00', '--job-id', '13060', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpkqv37ukb', '--error-file', '/tmp/tmpdomevcrq']
[2022-04-07 19:27:19,333] {standard_task_runner.py:80} INFO - Job 13060: Subtask create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task
[2022-04-07 19:27:19,725] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task scheduled__2018-12-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:27:20,197] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-12-01T00:00:00+00:00
[2022-04-07 19:27:20,199] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:27:20,272] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:27:20,333] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_posts_questions_bq_create_posts_questions_stack_overflow_data_partitioned_table_task_2018_12_01T00_00_00_00_00_82cd63cf602c52ec59b7cb0976a94de8
[2022-04-07 19:27:21,186] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2153, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2119, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1560, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1498, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1488, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Could not cast literal "creation_date" to type TIMESTAMP at [1:111]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_posts_questions_bq_create_posts_questions_stack_overflow_data_partitioned_table_task_2018_12_01T00_00_00_00_00_82cd63cf602c52ec59b7cb0976a94de8

[2022-04-07 19:27:21,234] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=load_to_BigQuery, task_id=create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task, execution_date=20181201T000000, start_date=20220407T192718, end_date=20220407T192721
[2022-04-07 19:27:21,313] {standard_task_runner.py:98} ERROR - Failed to execute job 13060 for task create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task (400 Could not cast literal "creation_date" to type TIMESTAMP at [1:111]

Location: us-central1
Job ID: airflow_load_to_BigQuery_create_external_posts_questions_bq_create_posts_questions_stack_overflow_data_partitioned_table_task_2018_12_01T00_00_00_00_00_82cd63cf602c52ec59b7cb0976a94de8
; 5019)
[2022-04-07 19:27:21,367] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-07 19:27:21,462] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:20:00,494] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task scheduled__2018-12-01T00:00:00+00:00 [queued]>
[2022-04-07 22:20:00,588] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task scheduled__2018-12-01T00:00:00+00:00 [queued]>
[2022-04-07 22:20:00,589] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:20:00,589] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:20:00,589] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:20:01,496] {taskinstance.py:1270} INFO - Executing <Task(BigQueryInsertJobOperator): create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task> on 2018-12-01 00:00:00+00:00
[2022-04-07 22:20:01,558] {standard_task_runner.py:52} INFO - Started process 7290 to run task
[2022-04-07 22:20:01,612] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task', 'scheduled__2018-12-01T00:00:00+00:00', '--job-id', '14315', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmplbuei4oz', '--error-file', '/tmp/tmp_9dqk4aa']
[2022-04-07 22:20:01,613] {standard_task_runner.py:80} INFO - Job 14315: Subtask create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task
[2022-04-07 22:20:02,082] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task scheduled__2018-12-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:20:02,338] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-12-01T00:00:00+00:00
[2022-04-07 22:20:02,341] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:20:02,433] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:20:02,506] {bigquery.py:1554} INFO - Inserting job ***_load_to_BigQuery_create_external_posts_questions_bq_create_posts_questions_stack_overflow_data_partitioned_table_task_2018_12_01T00_00_00_00_00_d96a750a14dc894ad702e3cf98770713
[2022-04-07 22:20:06,241] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_posts_questions.bq_create_posts_questions_stack_overflow_data_partitioned_table_task, execution_date=20181201T000000, start_date=20220407T222000, end_date=20220407T222006
[2022-04-07 22:20:06,306] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:20:06,377] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
