[2022-04-06 02:01:17,565] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: IngestToGCP.processing_tasks_posts_answers.download_files_posts_answers scheduled__2017-04-01T00:00:00+00:00 [queued]>
[2022-04-06 02:01:17,958] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: IngestToGCP.processing_tasks_posts_answers.download_files_posts_answers scheduled__2017-04-01T00:00:00+00:00 [queued]>
[2022-04-06 02:01:17,958] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 02:01:17,958] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-06 02:01:17,958] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-06 02:01:18,234] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): processing_tasks_posts_answers.download_files_posts_answers> on 2017-04-01 00:00:00+00:00
[2022-04-06 02:01:18,357] {standard_task_runner.py:52} INFO - Started process 156415 to run task
[2022-04-06 02:01:18,400] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'IngestToGCP', 'processing_tasks_posts_answers.download_files_posts_answers', 'scheduled__2017-04-01T00:00:00+00:00', '--job-id', '10835', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dag.py', '--cfg-path', '/tmp/tmpqtehv7t3', '--error-file', '/tmp/tmp118nwdwq']
[2022-04-06 02:01:18,402] {standard_task_runner.py:80} INFO - Job 10835: Subtask processing_tasks_posts_answers.download_files_posts_answers
[2022-04-06 02:01:19,088] {logging_mixin.py:109} INFO - Running <TaskInstance: IngestToGCP.processing_tasks_posts_answers.download_files_posts_answers scheduled__2017-04-01T00:00:00+00:00 [running]> on host 9fe4286b2855
[2022-04-06 02:01:19,781] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-06 02:01:20,006] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=IngestToGCP
AIRFLOW_CTX_TASK_ID=processing_tasks_posts_answers.download_files_posts_answers
AIRFLOW_CTX_EXECUTION_DATE=2017-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2017-04-01T00:00:00+00:00
[2022-04-06 02:01:20,008] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-06 02:01:20,009] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -A "Mozilla Chrome Safari" -sSfl --connect-timeout 5                     --retry 5                     https://storage.googleapis.com/dtc_data_lake_de-stack-overflow/processed/posts_answers-2017-04.csv > /opt/***/posts_answers-2017-04.csv']
[2022-04-06 02:01:20,286] {subprocess.py:85} INFO - Output:
[2022-04-06 02:01:31,357] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-06 02:01:32,889] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=IngestToGCP, task_id=processing_tasks_posts_answers.download_files_posts_answers, execution_date=20170401T000000, start_date=20220406T020117, end_date=20220406T020132
[2022-04-06 02:01:33,198] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-06 02:01:33,476] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
