[2022-04-07 19:23:23,994] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2016-05-01T00:00:00+00:00 [queued]>
[2022-04-07 19:23:24,067] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2016-05-01T00:00:00+00:00 [queued]>
[2022-04-07 19:23:24,069] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:23:24,069] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:23:24,070] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:23:24,412] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2016-05-01 00:00:00+00:00
[2022-04-07 19:23:24,427] {standard_task_runner.py:52} INFO - Started process 3269 to run task
[2022-04-07 19:23:24,446] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2016-05-01T00:00:00+00:00', '--job-id', '12807', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpxua12tsf', '--error-file', '/tmp/tmpmgq5kzua']
[2022-04-07 19:23:24,447] {standard_task_runner.py:80} INFO - Job 12807: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 19:23:24,641] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2016-05-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:23:24,724] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:23:24,781] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2016-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-05-01T00:00:00+00:00
[2022-04-07 19:23:24,787] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:23:25,250] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20160501T000000, start_date=20220407T192323, end_date=20220407T192325
[2022-04-07 19:23:25,298] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:23:25,392] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:16:44,312] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2016-05-01T00:00:00+00:00 [queued]>
[2022-04-07 22:16:44,336] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2016-05-01T00:00:00+00:00 [queued]>
[2022-04-07 22:16:44,337] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:16:44,337] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:16:44,337] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:16:44,492] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2016-05-01 00:00:00+00:00
[2022-04-07 22:16:44,502] {standard_task_runner.py:52} INFO - Started process 5562 to run task
[2022-04-07 22:16:44,514] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2016-05-01T00:00:00+00:00', '--job-id', '14060', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmp0m9vlx37', '--error-file', '/tmp/tmp7znho_s7']
[2022-04-07 22:16:44,515] {standard_task_runner.py:80} INFO - Job 14060: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 22:16:44,627] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2016-05-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:16:44,741] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:16:44,778] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2016-05-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2016-05-01T00:00:00+00:00
[2022-04-07 22:16:44,781] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:16:45,206] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20160501T000000, start_date=20220407T221644, end_date=20220407T221645
[2022-04-07 22:16:45,259] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:16:45,339] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
