[2022-04-07 19:26:36,655] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:36,837] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 19:26:36,837] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:36,837] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 19:26:36,837] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 19:26:37,606] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2018-07-01 00:00:00+00:00
[2022-04-07 19:26:37,624] {standard_task_runner.py:52} INFO - Started process 4705 to run task
[2022-04-07 19:26:37,653] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2018-07-01T00:00:00+00:00', '--job-id', '13011', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpemadbsxy', '--error-file', '/tmp/tmp4zyp1g7_']
[2022-04-07 19:26:37,662] {standard_task_runner.py:80} INFO - Job 13011: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 19:26:37,999] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [running]> on host 2c54f2187010
[2022-04-07 19:26:38,356] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 19:26:38,422] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2018-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-07-01T00:00:00+00:00
[2022-04-07 19:26:38,424] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 19:26:40,065] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20180701T000000, start_date=20220407T192636, end_date=20220407T192640
[2022-04-07 19:26:40,212] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 19:26:40,374] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-07 22:19:20,270] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:20,323] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [queued]>
[2022-04-07 22:19:20,323] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:20,323] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2022-04-07 22:19:20,323] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 22:19:20,983] {taskinstance.py:1270} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_badges.create_badges_stack_overflow_data_external_table> on 2018-07-01 00:00:00+00:00
[2022-04-07 22:19:21,001] {standard_task_runner.py:52} INFO - Started process 6925 to run task
[2022-04-07 22:19:21,029] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_to_BigQuery', 'create_external_badges.create_badges_stack_overflow_data_external_table', 'scheduled__2018-07-01T00:00:00+00:00', '--job-id', '14265', '--raw', '--subdir', 'DAGS_FOLDER/load_to_BigQuery_dag.py', '--cfg-path', '/tmp/tmpbhf3r8za', '--error-file', '/tmp/tmp2qf26aah']
[2022-04-07 22:19:21,031] {standard_task_runner.py:80} INFO - Job 14265: Subtask create_external_badges.create_badges_stack_overflow_data_external_table
[2022-04-07 22:19:21,283] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_BigQuery.create_external_badges.create_badges_stack_overflow_data_external_table scheduled__2018-07-01T00:00:00+00:00 [running]> on host 36107d30f64e
[2022-04-07 22:19:21,569] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-07 22:19:21,653] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_BigQuery
AIRFLOW_CTX_TASK_ID=create_external_badges.create_badges_stack_overflow_data_external_table
AIRFLOW_CTX_EXECUTION_DATE=2018-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-07-01T00:00:00+00:00
[2022-04-07 22:19:21,655] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-07 22:19:22,194] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=load_to_BigQuery, task_id=create_external_badges.create_badges_stack_overflow_data_external_table, execution_date=20180701T000000, start_date=20220407T221920, end_date=20220407T221922
[2022-04-07 22:19:22,239] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 22:19:22,723] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
